//Created by: Vyshakh P Rad
//Maintainer: Vyshakh P Rad

@Library('ls-jx-build-plugin@1.0') _

def APP_NAME = 'REPLACE_ME_APP_NAME';
def config = [
    APP_NAME                : "$APP_NAME",
    ORG                     : "REPLACE_ME_ORG",
    GIT_PROVIDER            : 'REPLACE_ME_GIT_PROVIDER',

    JX_AGENT                : "jenkins-scala",
    JX_DEF_CONTAINER        : "scala",
    JX_POD_TEMPLATE_BASE    : "scala",
    JX_HOME                 : "/home/jenkins", 
    JX_APP_ROOT             : ".",
    JX_BUILD_ROOT           : ".",
    JX_CHARTS_PATH          : "./charts/$APP_NAME",
];

lsBuild(config) {}