apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  {{- if .Values.blueGreenDeploy.enabled }}
  name: {{ template "bluename" . }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if or .Values.init .Values.blueGreenDeploy.blue.init }}
      initContainers:
{{- if and .Values.blueGreenDeploy.enabled .Values.blueGreenDeploy.blue.init }}
      - name: {{ .Chart.Name }}-init
        image: "{{ .Values.blueGreenDeploy.blue.init.image.repository }}:{{ .Values.blueGreenDeploy.blue.init.image.tag }}"
        imagePullPolicy: {{ .Values.blueGreenDeploy.blue.init.image.pullPolicy }}
{{- if .Values.blueGreenDeploy.blue.init.run }}
{{ toYaml .Values.blueGreenDeploy.blue.init.run | indent 8 -}}
{{- end }}
{{- else if .Values.init }}
      - name: {{ .Chart.Name }}-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.init.run }}
{{ toYaml .Values.init.run | indent 8 -}}
{{- end }}
{{- end }}
{{- if .Values.env.enabled }}
        env:
{{ toYaml .Values.env.values | indent 8 -}}
{{- end }}
        {{- if .Values.config.enabled }}
        volumeMounts:
        - mountPath: {{ .Values.config.mountPath }}
          name: {{ template "fullname" . }}
        {{- end }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
{{- if .Values.blueGreenDeploy.enabled }}
        image: "{{ .Values.blueGreenDeploy.blue.image.repository }}:{{ .Values.blueGreenDeploy.blue.image.tag }}"
        imagePullPolicy: {{ .Values.blueGreenDeploy.blue.image.pullPolicy }}
{{- if .Values.blueGreenDeploy.blue.run }}
{{ toYaml .Values.blueGreenDeploy.blue.run | indent 8 -}}
{{- end }}
{{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.run }}
{{ toYaml .Values.run | indent 8 -}}
{{- end }}
{{- end }}
{{- if .Values.env.enabled }}
        env:
{{ toYaml .Values.env.values | indent 8 -}}
{{- end }}
{{- if .Values.service.ports }}
        ports:
{{- range $ind , $port := .Values.service.ports }}
        - containerPort: {{ $port.targetPort }}
{{- end }}
{{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.probePort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.probePort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        {{- if .Values.config.enabled }}
        volumeMounts:
        - mountPath: {{ .Values.config.mountPath }}
          name: {{ template "fullname" . }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{ if .Values.config.enabled -}}
      volumes:
      - name: {{ template "fullname" . }}
        configMap:
          name: {{ template "fullname" . }}
      {{- end }}
