//Created by: Vyshakh P Rad
//Maintainer: Vyshakh P Rad

@Library('ls-jx-build-plugin@1.0') _

def APP_NAME = 'REPLACE_ME_APP_NAME';
def config = [
    APP_NAME                : "$APP_NAME",
    ORG                     : "REPLACE_ME_ORG",
    GIT_PROVIDER            : 'REPLACE_ME_GIT_PROVIDER',

    JX_AGENT                : "jenkins-go",
    JX_DEF_CONTAINER        : "go",
    JX_POD_TEMPLATE_BASE    : "go",
    JX_HOME                 : "/home/jenkins", 
    JX_APP_ROOT             : "/home/jenkins/go/src",
    JX_BUILD_ROOT           : "/home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_APP_NAME",
    JX_CHARTS_PATH          : "/home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_APP_NAME/charts/$APP_NAME",
];

lsBuild(config) {}